// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleCatalog: typeof import('./src/components/article/ArticleCatalog.vue')['default']
    ArticleEditor: typeof import('./src/components/article/ArticleEditor.vue')['default']
    ArticleListCard: typeof import('./src/components/common/ArticleListCard.vue')['default']
    ArticleMain: typeof import('./src/components/article/ArticleMain.vue')['default']
    ArticleSideBar: typeof import('./src/components/article/ArticleSideBar.vue')['default']
    Avatar: typeof import('./src/components/mongo-ui/avatar/index.vue')['default']
    BackTop: typeof import('./src/components/common/BackTop.vue')['default']
    BlogAvatar: typeof import('./src/components/mongo-ui/BlogAvatar.vue')['default']
    BlogButton: typeof import('./src/components/mongo-ui/button/BlogButton.vue')['default']
    BlogCard: typeof import('./src/components/mongo-ui/card/BlogCard.vue')['default']
    BlogFormItem: typeof import('./src/components/mongo-ui/form/form-item/BlogFormItem.vue')['default']
    BlogInput: typeof import('./src/components/mongo-ui/input/BlogInput.vue')['default']
    BlogMessage: typeof import('./src/components/mongo-ui/message/BlogMessage.vue')['default']
    BlogModal: typeof import('./src/components/mongo-ui/modal/BlogModal.vue')['default']
    BlogPagination: typeof import('./src/components/mongo-ui/pagination/BlogPagination.vue')['default']
    BlogPopover: typeof import('./src/components/mongo-ui/popover/BlogPopover.vue')['default']
    BlogSelect: typeof import('./src/components/mongo-ui/select/BlogSelect.vue')['default']
    BlogSwitch: typeof import('./src/components/mongo-ui/swtich/BlogSwitch.vue')['default']
    BlogUpload: typeof import('./src/components/mongo-ui/upload/BlogUpload.vue')['default']
    Button: typeof import('./src/components/mongo-ui/button/index.vue')['default']
    Card: typeof import('./src/components/mongo-ui/card/index.vue')['default']
    FormItem: typeof import('./src/components/mongo-ui/form/form-item/index.vue')['default']
    HeaderCover: typeof import('./src/components/common/HeaderCover.vue')['default']
    HomeArticleList: typeof import('./src/components/home/HomeArticleList.vue')['default']
    HomeSideBar: typeof import('./src/components/home/HomeSideBar.vue')['default']
    Input: typeof import('./src/components/mongo-ui/input/index.vue')['default']
    LoginModal: typeof import('./src/components/modal/LoginModal.vue')['default']
    Message: typeof import('./src/components/mongo-ui/message/index.vue')['default']
    Modal: typeof import('./src/components/mongo-ui/modal/index.vue')['default']
    MongoAvatar: typeof import('./src/components/mongo-ui/avatar/Mongo-Avatar.vue')['default']
    Pagination: typeof import('./src/components/mongo-ui/pagination/index.vue')['default']
    Popover: typeof import('./src/components/mongo-ui/popover/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchModal: typeof import('./src/components/modal/SearchModal.vue')['default']
    Select: typeof import('./src/components/mongo-ui/select/index.vue')['default']
    Swtich: typeof import('./src/components/mongo-ui/swtich/index.vue')['default']
    ToolBar: typeof import('./src/components/common/ToolBar.vue')['default']
    Upload: typeof import('./src/components/mongo-ui/upload/index.vue')['default']
  }
}

export {}
