// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleCatalog: typeof import('./src/components/article/ArticleCatalog.vue')['default']
    ArticleEditor: typeof import('./src/components/article/ArticleEditor.vue')['default']
    ArticleListCard: typeof import('./src/components/common/ArticleListCard.vue')['default']
    ArticleMain: typeof import('./src/components/article/ArticleMain.vue')['default']
    ArticleSideBar: typeof import('./src/components/article/ArticleSideBar.vue')['default']
    Avatar: typeof import('./src/components/mongo-ui/avatar/index.vue')['default']
    Backtop: typeof import('./src/components/mongo-ui/backtop/index.vue')['default']
    BackTop: typeof import('./src/components/mongo-ui/backtop/BackTop.vue')['default']
    Button: typeof import('./src/components/mongo-ui/button/index.vue')['default']
    Card: typeof import('./src/components/mongo-ui/card/index.vue')['default']
    Form: typeof import('./src/components/mongo-ui/form/form/index.vue')['default']
    FormItem: typeof import('./src/components/mongo-ui/form/form-item/index.vue')['default']
    HeaderCover: typeof import('./src/components/common/HeaderCover.vue')['default']
    HomeArticleList: typeof import('./src/components/home/HomeArticleList.vue')['default']
    HomeSideBar: typeof import('./src/components/home/HomeSideBar.vue')['default']
    Img: typeof import('./src/components/mongo-ui/img/index.vue')['default']
    Input: typeof import('./src/components/mongo-ui/input/index.vue')['default']
    LoginModal: typeof import('./src/components/common/LoginModal.vue')['default']
    Message: typeof import('./src/components/mongo-ui/message/index.vue')['default']
    Modal: typeof import('./src/components/mongo-ui/modal/index.vue')['default']
    Pagination: typeof import('./src/components/mongo-ui/pagination/index.vue')['default']
    Popover: typeof import('./src/components/mongo-ui/popover/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchModal: typeof import('./src/components/common/SearchModal.vue')['default']
    Select: typeof import('./src/components/mongo-ui/select/index.vue')['default']
    Switch: typeof import('./src/components/mongo-ui/switch/index.vue')['default']
    Swtich: typeof import('./src/components/mongo-ui/swtich/index.vue')['default']
    Tag: typeof import('./src/components/mongo-ui/tag/index.vue')['default']
    Timeline: typeof import('./src/components/mongo-ui/timeline/index.vue')['default']
    ToolBar: typeof import('./src/components/common/ToolBar.vue')['default']
    Upload: typeof import('./src/components/mongo-ui/upload/index.vue')['default']
  }
}

export {}
